name: lucide_info_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  all_lint_rules_community: ^0.0.31
  test: ^1.24.0
